### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by nanopils** [tomivirkki/react-vaadin-components#1]
### Current test stack

* [ ] typescript (^3.2.2)
* [ ] jest (^24.1.0)
* [ ] ts-jest (^23.10.5)
* [ ] enzyme (^3.8.0)
* [ ] enzyme-adapter-react-16 (^1.9.1)
* [ ] babel-jest (^24.1.0)
* [ ] jest-enzyme (^7.0.1)
* [ ] jest-css-modules (^1.1.0)

### Description

First of all, thanks for all the amazing work you've done!

I have now run my unit test via Wallaby.js for a while and noticed they all failed when I include this library. I thought it was an issue related to the Wallaby config itself. But to my dismay, when I run the unit tests via Jest, they all fail as well with the following error:

![react-vaadin-components failing unit tests](https://user-images.githubusercontent.com/1826339/52647192-86c52900-2ee4-11e9-9356-57ce11d17b33.png)

I have upgraded to the latest versions of react, jest and most libraries today in order to check if it fixed the issue. Unfortunately, it didn't help fixing the issue.

I think the issue is that Jest is using (jsdom)[https://www.npmjs.com/package/jsdom], which doesn't support web components.

Is there an easy/known way to fix this issue without having to rewrite all the tests from scratch (i.e. change test framework)?

Thanks a lot for your help.

### Versions

`
{
  npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.13.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.36',
  zlib: '1.2.11'
}
`

**Comment by tomivirkki** [comment]
Hi, thanks for the feedback :) I use a similar setup for the tests in this very library. However, in the test files I'm importing the component directly from the component file, (for example `import { FormItem } from 'react-vaadin-components/src/FormLayout'` instead of  `import { FormItem } from 'react-vaadin-components'`) and this excludes the import for `@webcomponents/webcomponentsjs` polyfill (that is defined in the `index.js` main file).

My guess is that a component gets imported somewhere inside `OrderedListColumnPicker` directly from `react-vaadin-components`, which is fine, but it has some caveats:

1. It automatically imports all the components from the library, even if you only need one
2. It automatically imports Web Components polyfill, even if you don't need to support IE11/Edge
3. Apparently it has some issues with testing tools

So I suggest switching the import from `import { Grid } from 'react-vaadin-components'` to `import { Grid } from 'react-vaadin-components/src/Grid'`. In case you also need the Web Components polyfill, remember to add the import for `@webcomponents/webcomponentsjs` in the app also. I've been meaning to add these instructions under the "Tutorial" section of the demo app and will do so before 1.0 release.

Note: I've just released a new version 0.8.0 which includes some file reorganization
Note 2: The import path of 'react-vaadin-components/src/Grid' still might change before 1.0 (considering changing 'src' to 'lib' etc...)

**Comment by nanopils** [comment]
Hi Tomi,

It seems that the actual problem is that es6 import statements isn't understood by jest. I have tried to fix this by modifying the .babelrc and the jest.config files, alas, to no avail.

I changed the import as you suggested by importing from `src/Grid.js` directly, but then the same error occurs on the first import of Grid.js.

![image](https://user-images.githubusercontent.com/1826339/52775581-50042580-3040-11e9-859e-e1ded71d4e37.png)

I'm not sure what's wrong with my setup. Any help is appreciated.

**Comment by tomivirkki** [comment]
I wonder if Babel env preset is correctly configured in your project? Example: https://github.com/tomivirkki/react-vaadin-components/blob/master/.babelrc#L2

**Comment by nanopils** [comment]
The issue was that we inherited a project that was using Parcel to build our react app. And Parcel refuses to transpile es6 in node_modules. This caused issues with both our unit tests and IE11.

Your solution to transpile the repo and its dependencies using those additional npm scripts made it work (here with Babel v.7):
`
"postinstall": "npm run prepare:es5",
"prepare:es5": "babel node_modules/@vaadin node_modules/@polymer node_modules/react-vaadin-components node_modules/@webcomponents/shadycss -x '.js' --out-dir ./ --relative --presets @babel/env,@babel/preset-react",
`
